var myApp = angular.module('myApp');
myApp.controller('areadashCtrl', ['$scope','ajax', '$state','R1Util',
    function ($scope,   ajax, $state,R1Util) {

        var vm = this;

        vm.serviceGrid = {
            enableRowSelection: true,
            enableRowHeaderSelection: false,
            multiSelect: false,
            enableSorting: true,
            enableFiltering: true,
            enableGridMenu: true,
            paginationPageSizes: [30, 50, 100]

        };


        vm.serviceGrid.columnDefs = [

            {
                field: 'areaCode',
                displayName: 'नंबर ',
                enableSorting: true,
                type: 'number',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "10%"
            },
            {
                field: 'areaName',
                displayName: 'गटाचे नाव',
                enableSorting: true,
                type: 'string',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "50%"
            },
            {
                field: 'panchayatName',
                displayName: 'पंचायत',
                enableSorting: true,
                type: 'string',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "30%"
            },

            {
                name: 'Action',
                enableSorting: false,
                enableCellEdit: false,
                width: "10%",
                cellTemplate: '<center><a role="button" ng-click="grid.appScope.vm.edit(grid, row)"><i class="bi bi-eye"></i></a>&nbsp &nbsp <a  role="button" ng-click="grid.appScope.vm.remove(grid, row)"><i class="bi bi-trash3"></i></a></center>'
            }
        ];



        vm.edit = function (grid, row) {
            var param = {
                action: 'view',
                id: row.entity.areaCode
            };

            $state.go('parent.sub.area', param);
        };


        vm.remove = function (grid, row) {

            if (row.entity.areaCode) {
                $scope.grid = grid;
                $scope.param = { "id": row.entity.areaCode };

                $scope.index = vm.serviceGrid.data.indexOf(row.entity);

                R1Util.createAlert($scope, "Warning", "Do You Want Delete Row", $scope.iConfirmFn);
            }
        }

        $scope.iConfirmFn = function () {
            ajax.delete('area', null, $scope.param).then(function (res) {
                $scope.grid.appScope.vm.serviceGrid.data.splice($scope.index, 1);
            })

        }

        vm.getRecords = function () {
            $(".loading").show();
            ajax.get('area/list', null).then(function (res) {
                if (res) {
                    vm.serviceGrid.data = res;
                }
                else {
                    var error = "Error";
                    if (res.error)
                        if (res.error.message)
                            error = res.error.message;
                    R1Util.createAlert($scope, "Error", error, null);
                }
                $(".loading").hide();
            },)
        }

        vm.getRecords();



    }

])

myApp.controller('areaCtrl', ['$scope', '$stateParams', '$q', 'ShareData', 'ajax', 'R1Util', 'Master', '$rootScope',
    function ($scope, $stateParams, $q, shareData, ajax, R1Util, Master, $rootScope) {

        var vm = this;
        $scope.Master = Master;

        vm.mode = 'new';
        // var pastEntity = {};

        if ($stateParams.action)
            vm.mode = $stateParams.action;

        vm.panchayats = [];


        vm.action = function () {
            var deffered = $q.defer();

            vm.navaction(function (res) {
                if (res == "OK")
                    deffered.resolve(res)
                else
                    deffered.reject(res)
            })
            return deffered.promise;
        }

        vm.navaction = function (fn) {
            switch (vm.mode) {
                case 'new':

                   vm.newrecord();
                    fn("OK")
                    break;
                case 'edit':

                    if (vm.entity.vch_id != undefined) {
                        if (NoViewing == true)
                        getExistEntity();
                        if (vm.entity.sh012.length != 0 || vm.entity.sh016.length != 0) {
                            vm.mode = 'undo'
                            R1Util.createAlert($scope, "WarningOk", "Can Not Edit a record Auto Generated by Share Issue ", null);
                        }
                    }
                    fn("OK")
                    break;

                case 'save':
                    $scope.save(function (res) {
                        fn(res)
                    });
                    break;


                case 'undo':
                    if (pastEntity)
                        vm.entity = angular.copy(pastEntity);
                    fn("OK")

                    break;


                case 'close':
                    fn("OK")
                    $rootScope.back();

                    break;

                default:
                    fn("OK")
                    break;
            }
        };

        $scope.save = function (fn) {
            if ($scope.areaform.$valid) {
                $(".loading").show();
                if (!vm.entity.areaCode)
                    ajax.post('area/insert', vm.entity).then(function (res) {
                        if (res) {

                            vm.entity.areaCode = res.areaCode;



                            // $scope.pushShareData();

                            $(".loading").hide();

                            $scope.message = "Record Saved Sucessfully";
                            R1Util.createAlert($scope, "Success", $scope.message, null);
                            pastEntity = angular.copy(vm.entity);
                            fn("OK");
                        }
                        else {
                            var error = "An Error has occured while saving record!";

                            if (res.error)
                                if (res.error.message)
                                    error = res.error.message;

                            vm.mode = 'edit';
                            $(".loading").hide();
                            R1Util.createAlert($scope, "Error", error, null);
                            fn("CANCEL")
                        }




                    })
                else {
                    ajax.put('area/update', vm.entity, { id: vm.entity.areaCode }).then(function (res) {
                        if (res) {



                            if (res) {

                                //    $scope.newarea.push(vm.entity);
                            }

                            // $scope.pushShareData();

                            $(".loading").hide();

                            $scope.message = "Record Saved Sucessfully";
                            R1Util.createAlert($scope, "Success", $scope.message, null);
                            pastEntity = angular.copy(vm.entity);
                            fn("OK");
                        }
                        else {
                            var error = "An Error has occured while saving record!";

                            if (res.error)
                                if (res.error.message)
                                    error = res.error.message;

                            vm.mode = 'edit';
                            $(".loading").hide();
                            R1Util.createAlert($scope, "Error", error, null);
                            fn("CANCEL")
                        }




                    })
                }

            }




        }

        // $scope.txn_type = [
        //    // s.c
        //     { "value": 1, 
        //       "name": "अनु.जाती " },
        //     //s.t
        //     { "value": 2,
        //      "name": "अनु.जमाती " },
        //     //v.j.a
        //     { "value": 3, 
        //     "name": "विमुक्ती जाती " },
        //     //n.t.c
        //     { "value": 4, 
        //     "name": "भटक्या जमाती-क  " },
        //     //n.t.d
        //     { "value": 5,
        //      "name": "भटक्या जमाती-ड  " },
        //     //maratha,vani
        //     { "value": 6,
        //      "name": "खुला प्रवर्ग " },
        //     //o.b.c
        //     { "value": 7, 
        //     "name": "ई.म.व " }
        // ];




        // vm.entity.txn_type = $scope.txn_type[0].value;

        // $scope.close = function () {
        //     // $state.go('parent.sub.cast', { action: 'close' });

        // }

        // $scope.numberOnly=function(e){
        //     if (/\D/g.test(e.value)) {
        //         e.value = e.value.replace(/\D/g, '');
        //       }
        // }

        var getPanchayats = function () {
            ajax.get("panchayat/list").then(function (res) {
                vm.panchayats = res;
                vm.entity.panchayatCode=1;
            }, function (err) {
                var e = err;
            })
        }

        vm.newrecord = function () {
            // pastEntity = vm.entity;
            vm.entity = {};

        }

        getExistEntity = function () {

            ajax.get('area/get', null, { id: vm.entity.areaCode }).then(function (res) {
                vm.entity = res;
                pastEntity = vm.entity;
            }, function (err) {

            })

        }

        $scope.init = function () {
            vm.entity = {};
            var q = $q.defer();

            var p = getPanchayats();
            $q.all([p]).then(function (res) {

                q.resolve();
            }, function (err) {

                q.reject();

            })

            return q.promise;


        }

        $scope.init().then(function (res) {
            vm.action();
            if ($stateParams.id) {
                vm.entity.areaCode = $stateParams.id;
                getExistEntity();
            }

        });



    }
])