
var myApp = angular.module('myApp');
myApp.controller('shareissuedashCtrl', ['$scope','$stateParams','$q',
    function ($scope,  $stateParams ,$q,) {

        var vm = this;
       // vm.entity = {};
        vm.mode = 'new';

        if ($stateParams.action)
            vm.mode = $stateParams.action;

        vm.serviceGrid = {
            enableRowSelection: true,
            enableRowHeaderSelection: false,
            multiSelect: false,
            enableSorting: true,
            enableFiltering: true,
            enableGridMenu: true,
            paginationPageSizes: [30, 50, 100, 70],
            paginationPageSize: 10
        };


        vm.serviceGrid.columnDefs = [

            {
                field: ' ',
                displayName: 'नंबर',
                enableSorting: true,
                type: 'number',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "20%"
            },
            {
                field: ' ',
                displayName: 'पूर्ण सभासद नंबर',
                enableSorting: true,
                type: 'string',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "20%"

            },
            {
                field: ' ',
                displayName: 'पूर्ण सभासद नंबर',
                enableSorting: true,
                type: 'string',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "20%"

            },
            {
                field: ' ',
                displayName: 'पूर्ण सभासद नाव',
                enableSorting: true,
                type: 'string',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "20%"

            },
            {
                field: ' ',
                displayName: 'अपूर्ण सभासद नाव',
                enableSorting: true,
                type: 'string',
                enableCellEdit: false,
                cellClass: 'alignLgrid',
                width: "10%"

            },
     {
                name: 'Action ',
                enableSorting: false,
                enableCellEdit: false,
                width: "10%",
                cellTemplate: '<center><a role="button" ng-click="grid.appScope.vm.edit(grid, row)"><i class="fa fa-eye fa-md"></i></a>&nbsp &nbsp <a  role="button" ng-click="grid.appScope.vm.remove(grid, row)"><i class="fa fa-trash fa-md"></i></a></center>'
            }
        ];




    }


])
myApp.controller('shareissueCtrl', ['$scope', '$stateParams','$q','$window',
    function ($scope, $stateParams,$q,$window) {

        var vm = this;
        vm.mode = 'new';
        vm.entity={};
        if ($stateParams.action)
            vm.mode = $stateParams.action;



        vm.action = function () {
            var deffered = $q.defer();
            vm.navaction(function (res) {
                if (res == "OK")
                    deffered.resolve(res)
                else
                    deffered.reject(res)
            })
            return deffered.promise;
        }

        vm.navaction = function (fn) {
            switch (vm.mode) {
                case 'new':

                    $scope.newrecord();
                    fn("OK")
                    break;
                case 'edit':
                   if (vm.entity.vch_id != undefined) {
                        if (NoViewing == true)
                            callbackEdit();
                        if (vm.entity.sh012.length != 0 || vm.entity.sh016.length != 0) {
                            vm.mode = 'undo'
                            R1Util.createAlert($scope, "WarningOk", "Can Not Edit a record Auto Generated by Share Issue ", null);
                        }
                    }
                    fn("OK")
                    break;

                    case 'save':
                        $scope.save(function (res) {
                            fn(res)
                        });
                    break;
              
                case 'undo':
                    // vm.params.postdatedchallan = null;
                    //  vm.params.rtgschallan = null;
                    fn("OK")

                    break;


                case 'close':
                    fn("OK")
                  //  $rootScope.back();
                  $window.history.back();
                
                    break;

                // case 'close':
                //     fn("OK")
                //     $rootScope.back();
                //     break;

                default:
                    fn("OK")
                    break;
            }
        };

        $scope.myarray = [];
        $scope.save = function (fn) {

            $scope.myarray.push(vm.entity);
            vm.serviceGrid = $scope.myarray;
            fn("OK")
            
        };
 

     
    }
])


